[package]
name = "da_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-lang = "0.28.0"
anchor-client = "0.28.0"
solana-sdk = "1.16"
bs58 = "0.5.0"
clap = {version="4.4.6", features = ['derive']}
blockroot = {path = "../solana_da_programs/programs/blockroot", features = ["no-entrypoint"]}
solana-rpc-client = "1.16"
anyhow = "1.0.75"
rand = "0.8.5"
hex = "0.4.3"

[workspace]