[package]
name = "sov-demo-prover-guest-mock"
version = "0.2.0"
edition = "2021"
resolver = "2"

[workspace]

[dependencies]
anyhow = "1.0.68"
risc0-zkvm = { version = "0.18", default-features = false, features = ["std"] }
risc0-zkvm-platform = "0.18"
sov-rollup-interface = { path = "../../../../../rollup-interface", features = ["mocks"] }
demo-stf = { path = "../../../stf" }
sov-risc0-adapter = { path = "../../../../../adapters/risc0" }

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2/v0.10.6-risc0" }

[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
debug = 1
lto = true

[profile.release.build-override]
opt-level = 3

