[package]
name = "sov-ibc"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
readme = "README.md"
publish = false
resolver = "2"

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["rc"] }
derive_more = { version = "0.99", default-features = false, features = ["from", "try_into"] }
sov-bank = { path = "../sov-bank", default-features = false }
sov-chain-state = { path = "../sov-chain-state", default-features = false }
sov-modules-api = { path = "../../sov-modules-api", default-features = false }
sov-modules-macros = { path = "../../sov-modules-macros" }
sov-state = { path = "../../sov-state", default-features = false }
sov-rollup-interface = { path = "../../../rollup-interface" }
schemars = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
uint = "0.9"

ibc = { workspace = true }
ibc-proto = { workspace = true }
prost = { version = "0.11", default-features = false }
tendermint = { version = "0.33", default-features = false }
tendermint-proto = {version = "0.33", default-features = false}


[dev-dependencies]
basecoin-app = { git = "https://github.com/informalsystems/basecoin-rs.git", rev = "7eaf3a7" }
basecoin-store = { git = "https://github.com/informalsystems/basecoin-rs.git", rev = "7eaf3a7" }
tendermint-testgen = { version = "0.33", default-features = false }
tokio = { workspace = true }
tower-abci = "0.10"
tower = { version = "0.4", features = ["full"] }
tempfile = { workspace = true }

[features]
default = ["native"]
serde = ["dep:serde", "dep:serde_json"]
native = ["serde", "sov-modules-api/native", "schemars"]