[package]
name = "template-stf"
version = { workspace = true }
edition = { workspace = true }
resolver = "2"
authors = { workspace = true }
license = { workspace = true }
homepage = "sovereign.xyz"
publish = false

[dependencies]
sov-modules-api = { path = "../../../module-system/sov-modules-api" }  
sov-state = { path = "../../../module-system/sov-state" } 
sov-accounts = { path = "../../../module-system/module-implementations/sov-accounts" } 
sov-bank = { path = "../../../module-system/module-implementations/sov-bank" } 
sov-sequencer-registry = { path = "../../../module-system/module-implementations/sov-sequencer-registry" } 
sov-modules-stf-template = { path = "../../../module-system/sov-modules-stf-template/" }
sov-stf-runner = { path = "../../../full-node/sov-stf-runner" } 
sov-sequencer = { path = "../../../full-node/sov-sequencer", optional = true } 
sov-rollup-interface = { path = "../../../rollup-interface" } 
tracing = { workspace = true }

serde_json = { workspace = true, optional = true }
serde = { workspace = true }
jsonrpsee = { workspace = true, optional = true }
borsh = { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true, optional = true }

[features]
default = []
native = [
	"sov-modules-api/native", 
	"sov-accounts/native", 
	"sov-bank/native", 
	"sov-sequencer-registry/native",
	"sov-modules-stf-template/native",
	"sov-stf-runner/native",   
    "serde_json", 
    "jsonrpsee",
    "sov-sequencer",
    "clap",
]
