[package]
name = "rollup-template"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
publish.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#stf dependencies
sov-modules-api = { path = "../../module-system/sov-modules-api", features = ["native"] }  
sov-state = { path = "../../module-system/sov-state" } 
sov-accounts = { path = "../../module-system/module-implementations/sov-accounts", features = ["native"]} 
sov-bank = { path = "../../module-system/module-implementations/sov-bank", features = ["native"] } 
sov-sequencer-registry = { path = "../../module-system/module-implementations/sov-sequencer-registry", features = ["native"] } 
sov-modules-stf-template = { path = "../../module-system/sov-modules-stf-template/", features = ["native"] }
sov-stf-runner = { path = "../../full-node/sov-stf-runner", features = ["native"] } 
borsh = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
serde_json = { workspace = true }
jsonrpsee = { workspace = true }
anyhow = { workspace = true }

template-risc0 = { path = "./provers/risc0" }
template-stf = { path = "./stf", features = ["native"] } 

sov-db = { path = "../../full-node/db/sov-db" } 
sov-sequencer = { path = "../../full-node/sov-sequencer" } 
sov-rollup-interface = { path = "../../rollup-interface", features = ["mocks"] } 
tokio = { workspace = true}

# Change dependencies here to use a different DA layer or ZKVM
sov-risc0-adapter = { path = "../../adapters/risc0", features = ["native"] }

# binary dependencies
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies]
tempfile = { workspace = true }

[features]
default = []

[[bin]]
name = "node"
path = "src/bin/node.rs"

[[bin]]
name = "cli_wallet"
path = "src/bin/cli_wallet.rs"

